from typing import Any

class ConnectionLost(Exception): ...

class Connection:
    def __init__(self, pool: Any) -> None: ...
    def close(self) -> None: ...
    def rollback(self) -> None: ...
    def reconnect(self) -> None: ...
    def __getattr__(self, name: Any): ...

class Transaction:
    def __init__(self, pool: Any, connection: Any) -> None: ...
    def close(self) -> None: ...
    def reopen(self) -> None: ...
    def reconnect(self) -> None: ...
    def __getattr__(self, name: Any): ...

class ConnectionPool:
    CP_ARGS: Any = ...
    noisy: bool = ...
    min: int = ...
    max: int = ...
    name: Any = ...
    openfun: Any = ...
    reconnect: bool = ...
    good_sql: str = ...
    running: bool = ...
    connectionFactory: Any = ...
    transactionFactory: Any = ...
    shutdownID: Any = ...
    dbapiName: Any = ...
    dbapi: Any = ...
    connargs: Any = ...
    connkw: Any = ...
    connections: Any = ...
    threadID: Any = ...
    threadpool: Any = ...
    startID: Any = ...
    def __init__(self, dbapiName: Any, *connargs: Any, **connkw: Any) -> None: ...
    def start(self) -> None: ...
    def runWithConnection(self, func: Any, *args: Any, **kw: Any): ...
    def runInteraction(self, interaction: Any, *args: Any, **kw: Any): ...
    def runQuery(self, *args: Any, **kw: Any): ...
    def runOperation(self, *args: Any, **kw: Any): ...
    def close(self) -> None: ...
    def finalClose(self) -> None: ...
    def connect(self): ...
    def disconnect(self, conn: Any) -> None: ...
